### ISSUE TITLE
v0.4.1: piqp-octave.tar.gz not gzipped

### ISSUE THREAD

**Issue by Schamschula** [PREDICT-EPFL/piqp#11]
As I was creating a MacPorts Portfile for `octave-piqp` tar failed. I checked the distribution archive
```
ports % file /opt/local/var/macports/distfiles/octave-piqp/piqp-octave.tar.gz
/opt/local/var/macports/distfiles/octave-piqp/piqp-octave.tar.gz: POSIX tar archive (GNU)
```
Hence, the archive was not compressed.

**Comment by RSchwan** [comment]
Should be fixed now. I updated all releases including the new Octave interface.
