### ISSUE TITLE
R Interface available

### ISSUE THREAD

**Issue by bnaras** [PREDICT-EPFL/piqp#2]
I wrote an R interface for piqp that is now available.  I will publish it on CRAN as soon as they return from the summer break. 

https://bnaras.github.io/piqp/index.html

Thank you.

**Comment by RSchwan** [comment]
Wow, that's amazing, thanks for all the effort.

In fact, I have also been working on an R interface myself (see the repo [here](https://github.com/PREDICT-EPFL/piqp-r)). It's based on [osqp-r](https://github.com/osqp/osqp-r), my limited knowledge of R, and some ideas from the [clarabel-r](https://github.com/oxfordcontrol/clarabel-r) package. I also sent it to an active R user for testing, before trying my luck with CRAN myself. Hence, the reason why I haven't advertised it yet.

Looking through your repo, I can see a lot of similarities, but also details and design decisions which are probably superior to what I threw together. Especially, considering your expertise in R. Hence, maybe we could take the best from both repos and combine them in a single package. For example, in your interface, the API for updating the data and thus reusing the ordering and factorization is missing. On the other side, your vignettes documentation is a nice addition.

**Comment by bnaras** [comment]
Thanks. Yes, I agree that the updating etc. are good to add, but this is all I did in between my day job on Friday.  I have also cleaned up some tests and will make them comprehensive. 

I am happy to take the best and merge them together. Also happy to move this under your Github org, just as I did for `clarabel-r` which I also authored. (I also maintain osqp-r!)

I should mention my interest is in making these solvers available to our package CVXR, the R cousin of cvxpy...

**Comment by bnaras** [comment]
The merge is now complete and the package is CRAN-ready as the [README](https://bnaras.github.io/piqp/index.html) badge shows. One Q I have is how strict we should be about C++14. This throws a note in CRAN checks if we insist on it (surmountable with comments to CRAN) but if we need to, why not insist on C++17?

**Comment by RSchwan** [comment]
C++17 also works, the minimum requirement is just C++14. I thought that it's better to specify the minimum requirement (in this case C++14), but if C++17 gets rid of the warning and makes it easier for CRAN we can also go with C++17.

**Comment by bnaras** [comment]
Ok, I'll leave it as C++14 for correctness. 

One last question. I think the package web page and repo more aptly belongs under your github org than mine as Clarabel-r does. Can we move it there? I can continue to maintain it so that would not be a problem.

**Comment by RSchwan** [comment]
Sure, this would be great. In this case, I'll remove/move the [repo](https://github.com/PREDICT-EPFL/piqp-r) on our end, so we can move/transfer your repo there. Or should I just push your code (with history) into a new repo in our org (after removing the old one), and add you as a contributor? Not sure what's easier.

**Comment by bnaras** [comment]
As long as I can commit, either one is fine, per your convenience.

**Comment by bnaras** [comment]
It's now on CRAN, so all done.

**Comment by RSchwan** [comment]
Awesome, thank you so much for all the effort.
