### ISSUE TITLE
Availability on conda-forge?

### ISSUE THREAD

**Issue by ilyanoskov** [PREDICT-EPFL/piqp#3]
First of all, I wanted to say big congratulations on your new amazing solver, it's the fastest one I have ever tried!

Could you please also publish it to conda forge as a package? Thank you very much in advance.

**Comment by RSchwan** [comment]
We are currently in the process of getting the package published to conda forge in the coming days (hopefully). Took some time to get it through the staging process.

**Comment by RSchwan** [comment]
PIQP has been published on conda-forge: https://github.com/conda-forge/piqp-feedstock
