### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by davidia** [PREDICT-EPFL/piqp#7]
I can see 8 CPU cores in use while solving using PIQP. I was wondering where that parallelism is coming from and is it possible to control it? E.g. use more than 8 threads to improve performance?

**Comment by RSchwan** [comment]
Strange, there should be no difference whether you use the conda-forge version or build it from source, except different compilers were used (which I doubt is the case). Also, are you using the dense or sparse interface? The ldlt factorization in the sparse interface is definitely not parallelized.

Anyway, I'm curious now. Maybe it's also coming from the python side, i.e., numpy does something under the hood. Could you maybe prepare a minimum working example where one observes the behavior? Then I could have a more detailed look.

**Comment by RSchwan** [comment]
Since there has been no followup, I'm closing the issue.
